#!/usr/bin/env python3
"""Generate a SearXNG settings.yml for private, proxy-routed local search.

SearXNG routes its OWN upstream engine requests through the rotating Webshare
proxies (round-robin over the list), so a private query never touches BrightData
or Nous -- only the search engines see it, and they see a Webshare IP. JSON API
is enabled (Hermes' searxng backend needs it) and the bot limiter is off (local
single-user). Re-run this whenever ~/.ghost/webshare_proxies.txt changes."""
import os, secrets

PROXIES = os.path.expanduser("~/.ghost/webshare_proxies.txt")
OUT_DIR = os.path.expanduser("~/.ghost/privacy/searxng")
OUT = os.path.join(OUT_DIR, "settings.yml")

proxies = []
try:
    with open(PROXIES) as f:
        for ln in f:
            ln = ln.strip()
            if ln and ln.count(":") >= 3:
                ip, port, user, pwd = ln.split(":", 3)
                proxies.append(f"http://{user}:{pwd}@{ip}:{port}")
except FileNotFoundError:
    pass

os.makedirs(OUT_DIR, exist_ok=True)
proxy_lines = "\n".join(f'        - "{p}"' for p in proxies)

settings = f"""# Auto-generated by gen_searxng_settings.py -- private proxy-routed search.
use_default_settings: true
server:
  secret_key: "{secrets.token_hex(32)}"
  limiter: false
  image_proxy: false
  method: "GET"
search:
  safe_search: 0
  formats:
    - html
    - json
outgoing:
  request_timeout: 30.0
  max_request_timeout: 40.0
  pool_connections: 100
  pool_maxsize: 50
  proxies:
    "all://":
{proxy_lines}
"""

open(OUT, "w").write(settings)
print(f"wrote {OUT} with {len(proxies)} rotating Webshare upstreams")
